feature/updated_integrated_NAICS_SIC_category_mappings
Factual/places pull request #24
Opened 2021-05-20 20:34 UTC by addieoh

Tied to this PLIN ticket: https://foursquare.atlassian.net/browse/PLIN-4507

2021-05-20 20:42 UTC, ewalker41 requested changes

2021-05-20 20:42 UTC, ewalker41 commented on categories/utils/Foursquare_to_NAICS_and_SIC.tsv
> +integrated_category_id	integrated_category_label	naics_code	sic_code
Can we make these `fsq_category_ids` and `fsq_category_labels` instead of integrated_category_x?

Also wondering if we should include the naics_label and sic_label for better inspection.  Thoughts?

2021-05-20 20:45 UTC, addieoh commented on categories/utils/Foursquare_to_NAICS_and_SIC.tsv
> +integrated_category_id	integrated_category_label	naics_code	sic_code
Yeah those should be relatively easy to pull!
Also, thoughts on leaving the category label in the hierarchy structure? I can break it out to just the category label instead if that's better for clients 🤔

2021-05-20 20:46 UTC, ewalker41 commented
Related note for @ynyway and @rossFactual - at some point we should probably make https://github.com/Factual/places/tree/master/categories/integrated_places_files the default category files for FSQ categories, instead of a subdirectory under Factual categories.  @rossFactual can you also raise w/ Ulas (?) about if/when we might have an equivalent public Foursquare-branded repo?

2021-05-20 21:08 UTC, ewalker41 commented on categories/utils/Foursquare_to_NAICS_and_SIC.tsv
> +integrated_category_id	integrated_category_label	naics_code	sic_code
I prefer to keep the full representation that aligns w/ our `fsq_category_labels`

2021-05-20 22:20 UTC, ewalker41 commented
What's your preference for updating or commenting on any categories that I may suggest we change?  In the PR or in the google doc?

Examples
```
13059	Dining and Drinking > Juice Bar	722410	Drinking Places (Alcoholic Beverages)
13033	Dining and Drinking > Cafes, Coffee, and Tea Houses > Bubble Tea Shop	722330	Mobile Food Services
13032	Dining and Drinking > Cafes, Coffee, and Tea Houses	72	Accommodation and Food Services
13105	Dining and Drinking > Restaurant > Chinese Restaurant > Chinese Breakfast Restaurant	722513	Limited-Service Restaurants
```

What's a limited-service Restaurant?

2021-05-20 22:31 UTC, addieoh commented
> What's your preference for updating or commenting on any categories that I may suggest we change? In the PR or in the google doc?

Google doc is probably easiest since there's code embedded into the sheet, but I don't have a strong pref :) 

> ```
> 13059	Dining and Drinking > Juice Bar	722410	Drinking Places (Alcoholic Beverages)
> 13033	Dining and Drinking > Cafes, Coffee, and Tea Houses > Bubble Tea Shop	722330	Mobile Food Services
> 13032	Dining and Drinking > Cafes, Coffee, and Tea Houses	72	Accommodation and Food Services
> 13105	Dining and Drinking > Restaurant > Chinese Restaurant > Chinese Breakfast Restaurant	722513	Limited-Service Restaurants
> ```
> 
> What's a limited-service Restaurant?

This is one that was originally in the sheet before I made edits, so I'm not entirely sure what the rationale was. I wonder if it's referring to... dimsum being limited service?? I'm going off this google definition:

A limited service restaurant, or “LSR” for short, is a restaurant in which service is kept to a minimum, and a customer's interactions with staff ends when the customer receives their food. The typical guest experience involves the guest ordering, paying for, and picking up their meal from a checkout counter.

2021-05-21 00:28 UTC, ynyway commented
Hi Addie! Sry just looking at this now. Do you mind making the columns that have the naics / sic labels wider ? also do u mind changing permissions s.t. i can make suggestions? 😅

2021-05-21 07:00 UTC, ewalker41 commented
OK we can make changes to the Google sheet...but which tab?

2021-05-21 22:13 UTC, addieoh commented
> OK we can make changes to the Google sheet...but which tab?

Yenny made her comments on the 3rd tab ("version w/ labels")!

2021-05-25 17:14 UTC, ynyway commented
@addieoh @ewalker41 when does this need to be reviewed and completed by? Jw so i can properly carve out time to review the rest of the mappings

2021-05-25 17:30 UTC, addieoh commented
> @addieoh @ewalker41 when does this need to be reviewed and completed by? Jw so i can properly carve out time to review the rest of the mappings

By monday should be fine!!

2021-05-25 17:36 UTC, ynyway commented
O great ok that's doable :) going to schedule time on my calendar to work through it today - Thurs then!! ill b done EOD THURS

2021-06-02 16:43 UTC, addieoh commented
pushed the newest version based on the annotations from the pasta party
going to double check that this file format is okay for Javi/Sidd's purposes too :)

2021-06-02 17:04 UTC, worace approved these changes

2021-06-07 18:53 UTC, ewalker41 approved these changes

2021-06-21 17:06 UTC, worace commented
@addieoh anything else to do here?

2021-07-06 16:50 UTC, ewalker41 commented
> @addieoh anything else to do here?

bump on this

cc: @soliz-factual

2021-07-08 15:40 UTC, merged